// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HideLauncher() {
  return window['go']['main']['App']['HideLauncher']();
}

export function LoadMessageContext(arg1) {
  return window['go']['main']['App']['LoadMessageContext'](arg1);
}

export function SearchHistory(arg1, arg2, arg3) {
  return window['go']['main']['App']['SearchHistory'](arg1, arg2, arg3);
}

export function SendChat(arg1) {
  return window['go']['main']['App']['SendChat'](arg1);
}

export function ShowLauncher() {
  return window['go']['main']['App']['ShowLauncher']();
}

export function ToggleLauncher() {
  return window['go']['main']['App']['ToggleLauncher']();
}
