// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function HideLauncher():Promise<void>;

export function ShowLauncher():Promise<void>;

export function ToggleLauncher():Promise<void>;
